config/routes.rb
Rails.application.routes.draw do

  get 'monstruos/default'

  get 'monstruos/index'

  get 'monstruos/new'

  get 'monstruos/show'

  get 'monstruos/edit'

  get 'monstruos/create'
  
  resources :monstruos

  root 'monstruos#default'

end

app/models/monstruo.rb
class Monstruo < ActiveRecord::Base
	validates :nombre,
		presence: true,
		uniqueness: true

	default_scope -> { order :nombre }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  add_flash_types :success, :warning, :danger, :info
end

app/controllers/monstruos_controller.rb
class MonstruosController < ApplicationController

  before_action :get_monstruo, only:[:show, :edit, :update]

  def get_monstruo
  	@monstruo = Monstruo.find(params[:id])
  end
  
  def index
  	@monstruos = Monstruo.all
  end

  def new
  	@monstruo = Monstruo.new
  end

  def show
  end

  def edit
  end

  def update
    if @monstruo.update_attributes(params.require(:monstruo).permit(:nombre, :edad))
      redirect_to monstruos_path, success: "Monstruo actualizado!!!"
    else
      flash[:notice] = "Hubo un error, intenta de nuevo."
    end
  end

  def create
  	@monstruo = Monstruo.new(params.require(:monstruo).permit(:nombre, :edad))
    if @monstruo.save
      redirect_to monstruos_path, success: "Monstruo creado!!!"
    else
      redirect_to monstruos_path, alert: "El monstruo ya existe."
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/monstruos_helper.rb
module MonstruosHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to root_path, class: 'navbar-brand' do%>
		<%= image_tag "logo.png", title: "Logo", class: "logo"%> Critter
	  <% end %>
    </div>
	<div class="btn-toolbar">
    <%= link_to monstruos_path, class: 'btn btn-primary btn-lg', role: 'button' do%>
      <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span> Listado de Monstruos
    <% end %>
    <%= link_to new_monstruo_path, class: 'btn btn-primary btn-lg', role: 'button' do%>
      <span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span> Crear Monstruo
    <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Critter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/header' %>

<div class="container">
	<% if flash[:notice] %>
    	<div class="alert alert-info"> <%= flash[:notice] %> </div>
  	<% end %>

	<% if flash[:success] %>
    	<div class="alert alert-success"> <%= flash[:success] %> </div>
  	<% end %>

  	<% if flash[:alert] %>
    	<div class="alert alert-danger"> <strong>Error: </strong> <%= flash[:alert] %> </div>
  	<% end %>
</div>
<%= yield %>

</body>
</html>

app/views/monstruos/_form.html.erb
<%= form_for @monstruo, html: {class: "form-inline"} do |f| %>

		<div class="form-group">
			<%= f.text_field :nombre, class: 'form-control', placeholder: 'Ingrese el nombre', required: true %>
			<%= f.number_field :edad, min: 0, class: 'form-control', placeholder: 'Edad' %>
		</div> <br>
		<%= f.submit "Guardar", class: 'btn btn-primary'%>
	<% end %>

app/views/monstruos/_monstruo.html.erb
<tr>
	<td>
		<%= link_to monstruo.nombre, monstruo %>
	</td>
	<td>
		<%= "#{monstruo.edad} años" %>
	</td>
</tr>

app/views/monstruos/default.html.erb
<div class="row">
		<h1 class="text-center col-md-6 col-md-offset-3">Bienvenido a Critter.<br><small>En Critter vas a poder saber lo que siempre quisiste de tus monsturos favoritos. Qué comen? Qué hacen cuando no asustan gente? Su pelicula favorita? Eso y más, acá en Critter.</small></h1>
</div>

app/views/monstruos/edit.html.erb
<div class="container">
	<h1>Editá el monstruo elegido</h1>

	<%= render 'form' %>
</div>

app/views/monstruos/index.html.erb
<div class="container">
	<h2>Todos los Monstruos</h2>
	<div class="container-fluid col-md-6 col-md-offset-3">
		<table class="table table-striped">
			<tr>
			    <th>Nombre</th>
			    <th>Edad</th>
			</tr>
			<%= render @monstruos %>
		</table>
	</div>
</div>

app/views/monstruos/new.html.erb
<div class="container">
	<h1>Creá un nuevo Monstruo</h1>

	<%= render 'form' %>
</div>

app/views/monstruos/show.html.erb
<div class="container">
	<h1><%= @monstruo.nombre %></h1>
	<h3><%= "#{@monstruo.edad} años" %></h3>
	<%= link_to edit_monstruo_path(@monstruo), class: 'btn btn-primary btn-lg', role: 'button' do%>
      <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> Editar
    <% end %>
</div>